### ISSUE TITLE
AttributeError: 'RAGHelperCloud' object has no attribute 'compressor'

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [AI-Commandos/RAGMeUp#11]
ERROR LOG:
```

INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: avsolatorio/GIST-small-Embedding-v0
Vectorizing documents: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 698/698 [00:54<00:00, 12.91it/s]
INFO:flashrank.Ranker:Downloading ms-marco-MultiBERT-L-12...
ms-marco-MultiBERT-L-12.zip: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 98.7M/98.7M [01:14<00:00, 1.38MiB/s]
 * Serving Flask app 'server'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.112:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [11/Aug/2024 21:35:52] "GET / HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [11/Aug/2024 21:35:53] "GET /favicon.ico HTTP/1.1" 404 -
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
ERROR:server:Exception on /chat [POST]
Traceback (most recent call last):
  File "/home/arslan/.virtualenvs/ragmeup/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arslan/.virtualenvs/ragmeup/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arslan/.virtualenvs/ragmeup/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arslan/.virtualenvs/ragmeup/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/arslan/Data/Learning/side_projects/RAGMeUp/server/server.py", line 37, in chat
    (new_history, response) = raghelper.handle_user_interaction(prompt, history)
  File "/home/arslan/Data/Learning/side_projects/RAGMeUp/server/RAGHelper_cloud.py", line 418, in handle_user_interaction
    reranked_docs = compute_rerank_provenance(self.compressor, user_query, reply['docs'], answer)
AttributeError: 'RAGHelperCloud' object has no attribute 'compressor'
INFO:werkzeug:127.0.0.1 - - [11/Aug/2024 21:37:10] "POST /chat HTTP/1.1" 500 -

```

**Comment by ErikTromp** [comment]
Will check this end of coming week because of holidays.

**Comment by Arslan-Mehmood1** [comment]
@ErikTromp  I've solved and created a pull request for it.
