### ISSUE TITLE
ImportError when starting server

### ISSUE THREAD

**Issue by ppe** [AI-Commandos/RAGMeUp#28]
With the latest version from main (sha 54a1ddcdbc5bef343c30cb997e58dbd6c8179dfe) I get the following error when starting the server with `python server.py`

```
Traceback (most recent call last):
  File "/Users/ppe/src/RAGMeUp_head/server/server.py", line 6, in <module>
    from RAGHelper_local import RAGHelperLocal
  File "/Users/ppe/src/RAGMeUp_head/server/RAGHelper_local.py", line 7, in <module>
    from RAGHelper import formatDocuments
ImportError: cannot import name 'formatDocuments' from 'RAGHelper' (/Users/ppe/src/RAGMeUp_head/server/RAGHelper.py)
```

The diff of my `.env` versus `.env.template` :
```
$ diff .env .env.template
6c6
< force_cpu=True
---
> force_cpu=False
8c8
< provenance_method=llm
---
> provenance_method=rerank
25c25
< data_directory='/tmp/RAGdata'
---
> data_directory='data'
38c38
< rerank=False
---
> rerank=True
78c77
< use_openai=True
---
> use_openai=False

```

Server starts up correctly at sha f4c75d6e7e7cad5a6a972b6c8fffedb512630f07

**Comment by ErikTromp** [comment]
Should be fixed if you pull master (and rerun `pip install -r requirements.txt`).

**Comment by ppe** [comment]
Hi, thank you but pulling master and rerunning pip results in 
```
Traceback (most recent call last):
  File "/Users/ppe/src/RAGMeUp_head/server/server.py", line 43, in <module>
    raghelper = RAGHelperCloud(logger)
  File "/Users/ppe/src/RAGMeUp_head/server/RAGHelper_cloud.py", line 48, in __init__
    self.initialize_rewrite_loops()
  File "/Users/ppe/src/RAGMeUp_head/server/RAGHelper_cloud.py", line 96, in initialize_rewrite_loops
    self.rewrite_ask_chain = self.create_rewrite_ask_chain()
  File "/Users/ppe/src/RAGMeUp_head/server/RAGHelper_cloud.py", line 108, in create_rewrite_ask_chain
    return {"context": context_retriever | RAGHelper.format_documents,
TypeError: unsupported operand type(s) for |: 'NoneType' and 'function'
```
when running `python server.py`

**Comment by ErikTromp** [comment]
I suppose you had rerank set to false? There was a bug indeed, fixed now.
