### ISSUE TITLE
TypeError from numpy when using SemanticChunker

### ISSUE THREAD

**Issue by ppe** [AI-Commandos/RAGMeUp#30]
Using the latest from HEAD. If I change from `RecursiveCharacterTextSplitter` to `SemanticChunker` for `splitter` with:
```
breakpoint_threshold_type=percentile
breakpoint_threshold_amount=None
number_of_chunks=None
```
I get the following traceback:

```
INFO:__main__:chunking the documents.
INFO:__main__:Initializing SemanticChunker splitter.
INFO:__main__:Chunking document(s).
Traceback (most recent call last):
  File "/Users/ppe/src/RAGMeUp_head/server/server.py", line 43, in <module>
    raghelper = RAGHelperCloud(logger)
  File "/Users/ppe/src/RAGMeUp_head/server/RAGHelper_cloud.py", line 45, in __init__
    self.load_data()
  File "/Users/ppe/src/RAGMeUp_head/server/RAGHelper.py", line 510, in load_data
    self._split_and_store_documents(docs)
  File "/Users/ppe/src/RAGMeUp_head/server/RAGHelper.py", line 336, in _split_and_store_documents
    self.chunked_documents = self._split_documents(docs)
  File "/Users/ppe/src/RAGMeUp_head/server/RAGHelper.py", line 325, in _split_documents
    for doc in self.text_splitter.split_documents(docs)
  File "/Users/ppe/src/RAGMeUp_head/server/lib/python3.10/site-packages/langchain_experimental/text_splitter.py", line 277, in split_documents
    return self.create_documents(texts, metadatas=metadatas)
  File "/Users/ppe/src/RAGMeUp_head/server/lib/python3.10/site-packages/langchain_experimental/text_splitter.py", line 262, in create_documents
    for chunk in self.split_text(text):
  File "/Users/ppe/src/RAGMeUp_head/server/lib/python3.10/site-packages/langchain_experimental/text_splitter.py", line 224, in split_text
    ) = self._calculate_breakpoint_threshold(distances)
  File "/Users/ppe/src/RAGMeUp_head/server/lib/python3.10/site-packages/langchain_experimental/text_splitter.py", line 140, in _calculate_breakpoint_threshold
    np.percentile(distances, self.breakpoint_threshold_amount),
  File "/Users/ppe/src/RAGMeUp_head/server/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4279, in percentile
    q = np.true_divide(q, 100)
TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
With `breakpoint_threshold_type=standard_deviation` I get:

```
  File "/Users/ppe/src/RAGMeUp_head/server/lib/python3.10/site-packages/langchain_experimental/text_splitter.py", line 146, in _calculate_breakpoint_threshold
    + self.breakpoint_threshold_amount * np.std(distances),
TypeError: can't multiply sequence by non-int of type 'numpy.float64'
```

**Comment by ErikTromp** [comment]
There was a type casting issue, this is fixed now. When using percentile, be sure to specify breakpoint_threshold_amount though (eg. 80)
