### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by marcojimenezgutierrez** [AI-Commandos/RAGMeUp#5]
I'm using default configuration from .env.template

`low_cpu_mem_usage` was None, now set to True since model is quantized.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.53s/it]
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: avsolatorio/GIST-small-Embedding-v0
Traceback (most recent call last):
  File "/mnt/c/bis/RAGMeUp/server/server.py", line 18, in <module>
    raghelper = RAGHelper(logger)
  File "/mnt/c/bis/RAGMeUp/server/RAGHelper.py", line 121, in __init__
    self.loadData()
  File "/mnt/c/bis/RAGMeUp/server/RAGHelper.py", line 326, in loadData
    bm25_retriever = BM25Retriever.from_texts(
  File "/home/marjimgu/.local/lib/python3.10/site-packages/langchain_community/retrievers/bm25.py", line 63, in from_texts
    vectorizer = BM25Okapi(texts_processed, **bm25_params)
  File "/home/marjimgu/.local/lib/python3.10/site-packages/rank_bm25.py", line 83, in __init__
    super().__init__(corpus, tokenizer)
  File "/home/marjimgu/.local/lib/python3.10/site-packages/rank_bm25.py", line 27, in __init__
    nd = self._initialize(corpus)
  File "/home/marjimgu/.local/lib/python3.10/site-packages/rank_bm25.py", line 52, in _initialize
    self.avgdl = num_doc / self.corpus_size
ZeroDivisionError: division by zero

**Comment by ErikTromp** [comment]
We need to fix this yes but for now: this is because there is no data in your data folder. Try adding at least one document.

**Comment by marcojimenezgutierrez** [comment]
Hello, thanks for your answer, I undertand. I've added 1 pdf. Here is one ScreenShot of the config, but still i got error. any idea?

![image](https://github.com/user-attachments/assets/849536e4-e943-4a17-8b2b-2c88333f1eb7)

**Comment by thistleknot** [comment]
I'm having this issue as well, despite me .env pointing to data
```
(textgen) [root@pve0 server]# cat .env | grep data
data_directory='data'

```

```
(textgen) [root@pve0 server]# ls data
'Autonomous clustering by fast find of mass and distance peaks.pdf'   test.txt
(textgen) [root@pve0 server]# python server.py
INFO:__main__:Instantiating the cloud RAG helper.
INFO:__main__:Initializing Ollama conversation.
INFO:__main__:Initializing embedding model avsolatorio/GIST-small-Embedding-v0 with params {'device': 'cuda'}.
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: avsolatorio/GIST-small-Embedding-v0
INFO:__main__:documents chunk pickle exists, reusing it.
INFO:__main__:Loading chunked documents.
INFO:__main__:Setting up Milvus Vector DB.
INFO:__main__:Loading data from existing store.
Vectorizing documents: 0it [00:00, ?it/s]
INFO:__main__:Initializing BM25Retriever.
Traceback (most recent call last):
  File "/data/RAGMeUp/server/server.py", line 128, in <module>
    raghelper = RAGHelperCloud(logger)
  File "/data/RAGMeUp/server/RAGHelper_cloud.py", line 52, in __init__
    self.load_data()
  File "/data/RAGMeUp/server/RAGHelper.py", line 564, in load_data
    self._setup_retrievers()
  File "/data/RAGMeUp/server/RAGHelper.py", line 491, in _setup_retrievers
    self._initialize_retrievers()
  File "/data/RAGMeUp/server/RAGHelper.py", line 464, in _initialize_retrievers
    self._initialize_bm25retriever()
  File "/data/RAGMeUp/server/RAGHelper.py", line 437, in _initialize_bm25retriever
    self.sparse_retriever = BM25Retriever.from_texts(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/langchain_community/retrievers/bm25.py", line 64, in from_texts
    vectorizer = BM25Okapi(texts_processed, **bm25_params)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/rank_bm25.py", line 83, in __init__
    super().__init__(corpus, tokenizer)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/rank_bm25.py", line 27, in __init__
    nd = self._initialize(corpus)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/rank_bm25.py", line 52, in _initialize
    self.avgdl = num_doc / self.corpus_size
ZeroDivisionError: division by zero

```

**Comment by thistleknot** [comment]
modified

RAGHelper.py

```
def _initialize_bm25retriever(self):
    """Initializes in memory BM25Retriever."""
    self.logger.info("Initializing BM25Retriever.")
    
    # Check if documents exist before initializing BM25
    if not self.chunked_documents:
        self.logger.warning("No documents found for BM25 initialization. Using empty document list.")
        self.sparse_retriever = None
        return
    
    self.sparse_retriever = BM25Retriever.from_texts(
        [x.page_content for x in self.chunked_documents],
        metadatas=[x.metadata for x in self.chunked_documents],
    )

def _setup_retrievers(self):
    """Sets up the retrievers based on specified configurations."""
    self._initialize_retrievers()
    
    # Set up the vector retriever
    self.logger.info("Setting up the Vector Retriever.")
    retriever = self.db.as_retriever(
        search_type="mmr", search_kwargs={"k": self.vector_store_k}
    )
    
    self.logger.info("Setting up the hybrid retriever.")
    if self.sparse_retriever is None:
        self.ensemble_retriever = retriever
    else:
        self.ensemble_retriever = EnsembleRetriever(
            retrievers=[self.sparse_retriever, retriever], weights=[0.5, 0.5]
        )
        
    if self.rerank:
        self._initialize_reranker()
```

**Comment by ErikTromp** [comment]
When using Milvus, you must have data in your data folder

**Comment by thistleknot** [comment]
I had data. For some reason it doesn't pick up files in the folder. So I
have to add them in manually AFTER patching the code to accept an empty
data folder (despite pdfs being in the data folder).

**Comment by ErikTromp** [comment]
Did you .env match your setup properly? Do your PDFs have actual content (not just OCR)? You can debug this by printing the loaders' output in load_data

**Comment by thistleknot** [comment]
Yes. Everything works when I push those same files in the folder using curl
but for some reason it's not pulling pdfs from the data folder on start.

Idk maybe it's because pdfs have spaces. Idk. But pushing via curl worked
after I modified the code to accept an empty list

**Comment by thistleknot** [comment]
Okay I'll look into the debug option. I did see a message related to
load_data

**Comment by ErikTromp** [comment]
That sounds like maybe your .env was modified? If vector_store_initial_load=True is set to False (preferred for Postgres, not default tho) you will see this error. Same if the data folder isnt configured well. Hard to say without knowing your .env contents

**Comment by thistleknot** [comment]
```
(textgen) [root@pve0 server]# ls data
'A landscape of consciousness- Toward a taxonomy of explanations and implications 1-s2.0-S0079610723001128-main.txt'
'Data Mining for Business Analyst - Galit Shmueli.txt'
'Deep Learning with Python 1732946436678.txt'
'Dive into Deep Learning 2106.11342v5.txt'
 Machine-Learning-Systems.txt
 Mastering-Python-Design-Patterns.txt
 MLM_w_P_JB.txt
'Modeling Creativity Case Studies in python 1410.0281.txt'
 python-basics-a-practical-introduction-to-python-3.txt


(base) [root@pve0 server]# cat .env
HF_TOKEN=
llm_model=gpt-3.5-turbo
llm_assistant_token="<|eot_id|>assistant\n\n"
embedding_model=avsolatorio/GIST-small-Embedding-v0
trust_remote_code=True
force_cpu=True

provenance_method=rerank
provenance_similarity_llm=sentence-transformers/distiluse-base-multilingual-cased-v2
provenance_include_query=False
provenance_llm_prompt="Instruction: You are a provenance auditor that needs to exactly determine how much an answer given to a user question was based on a given input document, knowing that more than just that one document were considered. Documents may be fully used verbatim, partially used or even translated. You need to give a score indicating how much a source document was used in creating the answer given to a user query, this score must be 0 = source document is not used at all, 1 = barely used, 2 = moderately used, 3 = mostly used, 4 = almost fully used and 5 = full text included in answer. You are forced to always answer only with the score from 0 to 5, don't explain yourself or add more text than just the score.

The user's query is:

{query}

The answer given is to this user query is:

{answer}

The source document that you need to score is the following:

{context}"

data_directory='data'
file_types="pdf,json,docx,pptx,xslx,csv,xml,txt"
json_schema="."
json_text_content=False
xml_xpath="//"

max_document_limit=10
vector_store=milvus
vector_store_uri='data.db'
vector_store_collection=ragmeup_documents
vector_store_sparse_uri=bm25_db.pickle
vector_store_initial_load=False
vector_store_k=13
document_chunks_pickle=rag_chunks.pickle
file_upload_using_llm=True
rerank=True
rerank_k=3
rerank_model=flashrank

temperature=0.2
repetition_penalty=1.1
max_new_tokens=2048

rag_instruction="Instruction: You are a digital librarian that can answer generic questions on relevant content quickly and succinctly. Here are a few documents from the library that you can use to answer the user's question, retrieved as documents from a database. Be sure to motivate your answer and always mention your source, so which of the documents you used to formulate the answer:

{context}"
rag_question_initial="The initial question you have to answer:

{question}"
rag_question_followup="The follow-up question you have to answer:

{question}"
rag_fetch_new_instruction="Instruction: You are a digital librarian with a database that contains relevant documents for user queries. Users want to ask questions based on those documents and ask questions that either need you to fetch new documents from the database or that are a followup question on previously obtained documents. You need to decide whether you are going to fetch new documents or whether the user is asking a follow-up question but you don't get to see the actual documents the user potentially is looking at.\nShould new documents be fetched from the database based on this user query? Answer with yes or no."
rag_fetch_new_question="The user question is the following: \"{question}\"\n"

use_rewrite_loop=True
rewrite_query_instruction="You have to answer a user question based on documents retrieved from a document database. It is your task to decide whether or not the documents contain the answer to the user's query. You can always only answer with exactly yes or no. The documents that are currently fetched from the database are:

{context}"
rewrite_query_question="The user's question is:

{question}"
rewrite_query_prompt="You are given a user query that should be answered by looking up documents that from a document store using a distance based similarity measure. The documents fetched from the document store were found to be irrelevant to answer the question. Rewrite the following question into an alternative that increases the likelihood of finding relevant documents from the database. You may only answer with the exact rephrasing. The original question is: {question}"

use_re2=True
re2_prompt="Read the question again: "

splitter='RecursiveCharacterTextSplitter'
chunk_size=858
chunk_overlap=429
breakpoint_threshold_type=percentile
breakpoint_threshold_amount=None
number_of_chunks=None

use_openai=False
openai_model_name='gpt-3.5-turbo'
use_gemini=False
gemini_model_name='gemini-pro'
GOOGLE_API_KEY='Your_API_key'
use_azure=False
use_ollama=True
#AZURE_OPENAI_ENDPOINT='http:\\192.168.3.17:5000\v1'
ollama_model='hf.co/bartowski/ibm-granite_granite-3.2-8b-instruct-GGUF:Q6_K_L'

deepeval_sample_size=200
deepeval_qa_pairs=10
deepeval_answer_relevancy_threshold=0.7
deepeval_faithfulness_threshold=0.7
deepeval_contextual_precision_threshold=0.7
deepeval_contextual_recall_threshold=0.7
deepeval_contextual_relevancy_threshold=0.7
deepeval_hallucination_threshold=0.5
deepeval_correctness_threshold=0.5
deepeval_question_instruction="You direct another LLM with questions. Write a question we can ask to an LLM that it will be able to answer based on these existing documents. Make sure the question can be accurately answered using the documents' contents and never ever reply with anything else but the question we need to supply to the LLM:
{context}"
deepeval_question_query="Generate a question to that can be answered given the input documents, nothing else but the question and no explanation."
deepeval_answer_instruction="You are a digital librarian and need to answer questions based on input documents. Here are the documents you are forced to base your answer on:

{context}"
deepeval_answer_query="Answer the following question, never give any explanation or other output than the generated article itself:

{question}"


ragas_sample_size=200
ragas_qa_pairs=10
ragas_timeout=300
ragas_max_workers=1
ragas_question_instruction="You direct another LLM with questions. Write a question we can ask to an LLM that it will be able to answer based on these existing documents. Make sure the question can be accurately answered using the documents' contents and never ever reply with anything else but the question we need to supply to the LLM:

{context}"
ragas_question_query="Generate a question to that can be answered given the input documents, nothing else but the question and no explanation."
ragas_answer_instruction="You are a digital librarian and need to answer questions based on input documents. Here are the documents you are forced to base your answer on:

{context}"
ragas_answer_query="Answer the following question, never give any explanation or other output than the generated article itself:

{question}"

(textgen) [root@pve0 server]# python server.py
INFO:__main__:Instantiating the cloud RAG helper.
INFO:__main__:Initializing Ollama conversation.
INFO:__main__:Initializing embedding model avsolatorio/GIST-small-Embedding-v0 with params {'device': 'cpu'}.
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: avsolatorio/GIST-small-Embedding-v0
INFO:__main__:documents chunk pickle exists, reusing it.
INFO:__main__:Loading chunked documents.
INFO:__main__:Setting up Milvus Vector DB.
INFO:__main__:Loading data from existing store.
Vectorizing documents: 0it [00:00, ?it/s]
INFO:__main__:Initializing BM25Retriever.
WARNING:__main__:No documents found for BM25 initialization. Using empty document list.
INFO:__main__:Setting up the Vector Retriever.
INFO:__main__:Setting up the hybrid retriever.
INFO:__main__:Setting up the FlashrankRerank.
INFO:__main__:Setting up the ContextualCompressionRetriever.
INFO:__main__:Initializing RAG chains for fetching new documents.
 * Serving Flask app 'server'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.3.18:5000
INFO:werkzeug:Press CTRL+C to quit

```

so I add the documents like so

```
for file in *.txt; do curl -X POST -F "file=@\"$file\"" http://localhost:5000/add_document; done
```

**Comment by ErikTromp** [comment]
Ah I think I see the problem now. A bit annoying at times and maybe should get rid of it but RAG Me Up caches the Milvus DB and document chunks too. If you booted the server once without legit files, those caches will be empty moving forward. 

Remove the file that is set under:
document_chunks_pickle=

And potentially once off also delete your Milvus DB. The idea used to be we load everything from the data directory only once in bulk and then you evolve from there on by adding a file at a time. This goes wrong obviously when you start off running the server without the final bulk load of data present.

**Comment by thistleknot** [comment]
great.  I will do that.  Any thoughts on how to delete stuff from the
db['s]?

**Comment by ErikTromp** [comment]
Deletion should work but I havent tried Milvus in ages so perhaps they renamed the default collection name or something. You can actually start a Python shell and query your Milvus DB on disk to see what it looks like.

Apart from that, delete the .db file and reload all documents always works.
