### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vdefeo** [AI-Commandos/RAGMeUp#6]
Hello, I'm trying to run the application locally on a Mac M3 and receiving the following error when trying to create the Milvus database.

https://github.com/AI-Commandos/RAGMeUp/blob/main/server/RAGHelper.py#L318

I'm receiving the following error:

```
Traceback (most recent call last):
  File "/Users/vdefeo/.pyenv/versions/3.12.4/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vdefeo/.pyenv/versions/3.12.4/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/vdefeo/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/vdefeo/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/vdefeo/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/vdefeo/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vdefeo/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/vdefeo/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/vdefeo/projects/github/RAGMeUp/server/server.py", line 18, in <module>
    raghelper = RAGHelper(logger)
                ^^^^^^^^^^^^^^^^^
  File "/Users/vdefeo/projects/github/RAGMeUp/server/RAGHelper.py", line 125, in __init__
    self.loadData()
  File "/Users/vdefeo/projects/github/RAGMeUp/server/RAGHelper.py", line 312, in loadData
    self.db = Milvus.from_documents(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vdefeo/projects/github/RAGMeUp/.venv/lib/python3.12/site-packages/langchain_core/vectorstores/base.py", line 1058, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vdefeo/projects/github/RAGMeUp/.venv/lib/python3.12/site-packages/langchain_milvus/vectorstores/milvus.py", line 1183, in from_texts
    vector_db.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/Users/vdefeo/projects/github/RAGMeUp/.venv/lib/python3.12/site-packages/langchain_milvus/vectorstores/milvus.py", line 700, in add_texts
    embeddings = self.embedding_func.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vdefeo/projects/github/RAGMeUp/.venv/lib/python3.12/site-packages/langchain_huggingface/embeddings/huggingface.py", line 87, in embed_documents
    embeddings = self.client.encode(
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/vdefeo/projects/github/RAGMeUp/.venv/lib/python3.12/site-packages/sentence_transformers/SentenceTransformer.py", line 565, in encode
    if all_embeddings[0].dtype == torch.bfloat16:
       ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

It looks like this error happened because the list of documents is empty. Have you seen this before?

Thanks!

**Comment by ErikTromp** [comment]
Not sure but I had this error too once, which I resolved by upgrading Milvus. The current requirements.txt should contain the most recent, working version. Can you check if that solves it?

**Comment by vdefeo** [comment]
The issue is that I updated `sentence-transformers` to 3.0.0+ and it seems it is incompatible with the latest version of langchain-milvus.
